"""empty message

Revision ID: 32af209364e0
Revises: 44045a4476a6
Create Date: 2020-07-15 12:14:13.825861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32af209364e0'
down_revision = '44045a4476a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Nickname', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['Nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'Nickname')
    # ### end Alembic commands ###
