"""empty message

Revision ID: 5e237346ae3a
Revises: cca0e81ea116
Create Date: 2020-07-15 12:26:46.803269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e237346ae3a'
down_revision = 'cca0e81ea116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Nickname', table_name='users')
    op.drop_column('users', 'Nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Nickname', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('Nickname', 'users', ['Nickname'], unique=True)
    # ### end Alembic commands ###
