"""empty message

Revision ID: 71d171118b1e
Revises: e8f2fe3c83a5
Create Date: 2020-07-15 13:35:29.837141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d171118b1e'
down_revision = 'e8f2fe3c83a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('face', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('face', 'user', ['face'], unique=True)
    # ### end Alembic commands ###
