"""empty message

Revision ID: 79921e0b1c04
Revises: 7019028ca54b
Create Date: 2020-07-14 18:01:45.422026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79921e0b1c04'
down_revision = '7019028ca54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('add_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'add_time')
    # ### end Alembic commands ###
