"""empty message

Revision ID: 8b0accf7c2e4
Revises: e037530abdce
Create Date: 2020-07-19 18:41:00.322038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b0accf7c2e4'
down_revision = 'e037530abdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preview', sa.Column('cover_picture', sa.String(length=255), nullable=True))
    op.drop_index('logo', table_name='preview')
    op.create_unique_constraint(None, 'preview', ['cover_picture'])
    op.drop_column('preview', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preview', sa.Column('logo', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'preview', type_='unique')
    op.create_index('logo', 'preview', ['logo'], unique=True)
    op.drop_column('preview', 'cover_picture')
    # ### end Alembic commands ###
