"""empty message

Revision ID: c9c896d5cdd3
Revises: 8b0accf7c2e4
Create Date: 2020-09-25 16:28:26.861198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c896d5cdd3'
down_revision = '8b0accf7c2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_log', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_log', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_log', type_='foreignkey')
    op.drop_column('user_log', 'admin_id')
    # ### end Alembic commands ###
