"""empty message

Revision ID: cca0e81ea116
Revises: a2caf7a4c1bb
Create Date: 2020-07-15 12:25:08.170432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cca0e81ea116'
down_revision = 'a2caf7a4c1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.drop_index('Nickname', table_name='user')
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.drop_column('user', 'Nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Nickname', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('Nickname', 'user', ['Nickname'], unique=True)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
