"""empty message

Revision ID: e037530abdce
Revises: 71d171118b1e
Create Date: 2020-07-16 05:02:40.488891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e037530abdce'
down_revision = '71d171118b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_admin_add_time'), 'admin', ['add_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_add_time'), table_name='admin')
    op.drop_column('admin', 'add_time')
    # ### end Alembic commands ###
